connection.dialect = org.hibernate.dialect.PostgreSQLDialect
connection.driver_class = org.postgresql.Driver
connection.url = jdbc:postgresql://postgres:5432/dhis2
connection.username = dhis_tl
connection.password = 123456
connection.schema = update
encryption.password = xxxx
